# Generated by Django 5.2.11 on 2026-02-16 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('core_centroid', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('provider_type', models.CharField(choices=[('rss', 'RSS Feed'), ('hackernews', 'Hacker News'), ('subreddit', 'Subreddit')], max_length=50)),
                ('config', models.JSONField(default=dict)),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('error', 'Error'), ('paused', 'Paused')], default='healthy', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='canopyresearch.workspace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=2000)),
                ('content', models.TextField()),
                ('published_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='canopyresearch.source')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='canopyresearch.workspace')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['owner', '-updated_at'], name='canopyresea_owner_i_e14efa_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['workspace', 'status'], name='canopyresea_workspa_6d731a_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['workspace', '-last_fetched'], name='canopyresea_workspa_6caf20_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together={('workspace', 'name')},
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['workspace', '-published_at'], name='canopyresea_workspa_d57921_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['workspace', 'source', '-published_at'], name='canopyresea_workspa_8dd499_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['workspace', 'hash'], name='canopyresea_workspa_1eeeed_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('hash__gt', '')), fields=('workspace', 'hash'), name='unique_doc_hash_per_workspace'),
        ),
    ]
