# Generated by Django 5.2.11 on 2026-02-17 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canopyresearch', '0002_refactor_document_source_many_to_many'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('documents_found', models.IntegerField(default=0)),
                ('documents_created', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], max_length=20)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='document',
            name='unique_doc_hash_per_workspace',
        ),
        migrations.RemoveConstraint(
            model_name='documentsource',
            name='canopyresearch_documentsource_unique_document_source',
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='canopyresea_workspa_1eeeed_idx',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='hash',
            new_name='content_hash',
        ),
        migrations.RenameIndex(
            model_name='documentsource',
            new_name='canopyresea_source__663ddf_idx',
            old_name='canopyresea_source__discovered_at_idx',
        ),
        migrations.AddField(
            model_name='document',
            name='external_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='ingested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='raw_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='auto_pause_threshold',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='source',
            name='consecutive_failures',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='source',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='source',
            name='last_successful_fetch',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='documentsource',
            unique_together={('document', 'source')},
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['workspace', 'content_hash'], name='canopyresea_workspa_a243e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('content_hash__gt', '')), fields=('workspace', 'content_hash'), name='unique_doc_content_hash_per_workspace'),
        ),
        migrations.AddField(
            model_name='ingestionlog',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_logs', to='canopyresearch.source'),
        ),
        migrations.AddIndex(
            model_name='ingestionlog',
            index=models.Index(fields=['source', '-started_at'], name='canopyresea_source__f64271_idx'),
        ),
    ]
