# Generated by Django 5.2.11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('canopyresearch', '0003_phase2_model_enhancements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centroid', models.JSONField(blank=True, default=list)),
                ('size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='canopyresearch.workspace')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ClusterMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='canopyresearch.cluster')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_memberships', to='canopyresearch.document')),
            ],
            options={
                'unique_together': {('document', 'cluster')},
            },
        ),
        migrations.CreateModel(
            name='WorkspaceCoreFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('up', 'Thumbs Up'), ('down', 'Thumbs Down')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_feedback_entries', to='canopyresearch.document')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_feedback', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_feedback', to='canopyresearch.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceCoreSeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_source', models.CharField(choices=[('auto', 'Auto-seeded from workspace description'), ('manual', 'Manually selected')], default='auto', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_seed_entries', to='canopyresearch.document')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_seeds', to='canopyresearch.workspace')),
            ],
            options={
                'unique_together': {('workspace', 'document')},
            },
        ),
        migrations.AddIndex(
            model_name='workspacecoreseed',
            index=models.Index(fields=['workspace', '-created_at'], name='canopyresea_workspa_created_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacecorefeedback',
            index=models.Index(fields=['workspace', '-created_at'], name='canopyresea_workspa_feedback_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacecorefeedback',
            index=models.Index(fields=['document', 'vote'], name='canopyresea_documen_vote_idx'),
        ),
        migrations.AddIndex(
            model_name='cluster',
            index=models.Index(fields=['workspace', '-updated_at'], name='canopyresea_workspa_cluster_idx'),
        ),
        migrations.AddIndex(
            model_name='clustermembership',
            index=models.Index(fields=['cluster', '-assigned_at'], name='canopyresea_cluster_assigned_idx'),
        ),
        migrations.AddIndex(
            model_name='clustermembership',
            index=models.Index(fields=['document'], name='canopyresea_documen_membership_idx'),
        ),
    ]
