# Generated by Django 5.2.11 on 2026-03-06 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canopyresearch', '0008_populate_initial_search_terms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-relevance', '-published_at']},
        ),
        migrations.RenameIndex(
            model_name='cluster',
            new_name='canopyresea_workspa_939f3e_idx',
            old_name='canopyresea_workspa_cluster_idx',
        ),
        migrations.RenameIndex(
            model_name='cluster',
            new_name='canopyresea_workspa_2d16d4_idx',
            old_name='canopyresea_workspa_alignment_idx',
        ),
        migrations.RenameIndex(
            model_name='cluster',
            new_name='canopyresea_workspa_e78e71_idx',
            old_name='canopyresea_workspa_velocity_idx',
        ),
        migrations.RenameIndex(
            model_name='clustermembership',
            new_name='canopyresea_cluster_ba1aca_idx',
            old_name='canopyresea_cluster_assigned_idx',
        ),
        migrations.RenameIndex(
            model_name='clustermembership',
            new_name='canopyresea_documen_f0d748_idx',
            old_name='canopyresea_documen_membership_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='canopyresea_workspa_1b3dc5_idx',
            old_name='canopyresea_doc_relevance_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='canopyresea_workspa_fd51fa_idx',
            old_name='canopyresea_doc_alignment_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='canopyresea_workspa_f74853_idx',
            old_name='canopyresea_doc_velocity_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='canopyresea_workspa_52f528_idx',
            old_name='canopyresea_doc_novelty_idx',
        ),
        migrations.RenameIndex(
            model_name='workspacecorefeedback',
            new_name='canopyresea_workspa_3b5400_idx',
            old_name='canopyresea_workspa_feedback_idx',
        ),
        migrations.RenameIndex(
            model_name='workspacecorefeedback',
            new_name='canopyresea_documen_aef484_idx',
            old_name='canopyresea_documen_vote_idx',
        ),
        migrations.RenameIndex(
            model_name='workspacecoreseed',
            new_name='canopyresea_workspa_ddbd1b_idx',
            old_name='canopyresea_workspa_created_idx',
        ),
        migrations.RenameIndex(
            model_name='workspacesearchterms',
            new_name='canopyresea_workspa_00be62_idx',
            old_name='canopyresea_workspace_idx',
        ),
        migrations.RenameIndex(
            model_name='workspacesearchterms',
            new_name='canopyresea_workspa_352ffe_idx',
            old_name='canopyresea_source_idx',
        ),
    ]
