# Generated by Django 5.2.11 on 2026-03-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canopyresearch', '0009_alter_document_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='ingestion_interval_hours',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How often to auto-ingest (hours). Leave blank to disable scheduled ingestion.', null=True),
        ),
    ]
