# Generated by Django 5.2.11 on 2026-03-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canopyresearch', '0010_workspace_ingestion_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='label',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
